/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'uid' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllStudentsSortedByEmail' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'updateStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'uid' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllStudentsSortedByEmail' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'updateStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };